### ISSUE TITLE
Envs

### ISSUE THREAD

**Issue by denisovkiv** [acetone415/talkback_bot#5]
Трувэй - подтягивать переменные конфига из окружения

https://pypi.org/project/environs/

```python
FOO = env.str(‘FOO’, default=‘bar’)
```

`.env`  можно убрать в `.gitignore`, а можно не убирать, выпилив секреты.

Соответственно при запуске чекать, все ли конфиги для корректной работы присутствуют. Если нет - слать в хер

**Comment by acetone415** [comment]
Thanx bro)
